### Q. What is Feature Extraction from text? and why we need it?
- Lets say u have a textual data to feed to ML Model. eg- Sentiment analysis from the text.
- Problem is ML Algo can not understand text it can understand number only. 
- Process of converting Text into number are called Feature Extraction from text (aka-text_representation or text_vectorisation)


### Q. Why is it difficult?
- for Image data input is pixles and pixle values are already in number so easy to convert
- speach is Web form and amplitude can be found out in periodic interval in number and can be stored in array and used as an input. hence easy to handle.
- Lets we have an english sentence "Hello How are you?" and we have to find whether sentiment is +ve, +-ve or neutral?  as it is not directly numerical form it is diffcult for ML Model to handel.

### Q. What is the core Idea?
- Our Goal should be that after converson number should tell the semantic meaning to the text. If Numbers does not represent semetic meaning ML will not perform well.

### Q What are the techniques?
1.  One Hot Encoding
2.  Bag of Words
3.  n-grams
4.  Tf-idf
5.  Custom feature (eg- avg size of words)
6.  Word2vec (aka-Embedding)


# Common Terms 
### 1. Corpus (c)-
    Combination all the words in the dataset (including repeatations) eg- I felt happy because I saw the others were happy.  Here corpus= [I, felt, happy, because, I, saw, the, others, were, happy]

### 2. Vocabulary (v)-
    Unique Words to make the Corpus. Vocabulary= [I, felt, happy, because, saw, the, others, were]
### 3. Document (d)-
    Lets say we have 30,000 revies of a movie then each review is one document
### 4. Word (w)- 
    Individual word of each document.

# One  Hot Encoding

Document   | Text                |
:---------|:----------------------|
| D1      | People watch campusx  |
| D2      | campusx watch campusx |
| D3      | People write comment  |
| D4     | campusx write comment |



Corpus-
people watch campusx campusx watch campusx 
people write comment campusx write comment

vocabulary-
people watch campusx write comment
v=5

words


one hot encoding tells that convert each words of document in v-dimension vector

|Word          |People | Watch | campusx| write| comment|
:-------------|:----------------|:-----|:------|:-------|:-----|
| people      | 1    |0      |0       |0     |0       | 
| watch       | 0    |1      |0       |0     |0       | 
| campusx     | 0    |0      |1       |0     |0       | 
| write       | 0    |0      |0       |1     |0       | 
| comment     | 0    |0      |0       |0     |1       | 

######

Document   | Text                |array|
:---------|:---------------------|:---|
| D1      | People watch campusx  |[ [1,0,0,0,0], [0,1,0,0,0], [0,0,1,0,0] ]| 
| D2      | campusx watch campusx |[ [0,0,1,0,0], [0,1,0,0,0], [0,0,1,0,0] ]| 
| D3      | People write comment  |[ [1,0,0,0,0], [0,0,0,1,0], [0,0,0,0,1] ]| 
| D4     | campusx write comment  | [ [0,0,1,0,0], [0,0,0,1,0], [0,0,0,0,1] ]| 
| D5     | watch campusx write comment  | [ [0,1,0,0,0],  [0,0,1,0,0], [0,0,0,1,0], [0,0,0,0,1] ]| 
###

### Pros of OHE-
- it is very intutive
- easy to implement

### Flaws of OHE- 
- Sparsity( many zeros in the array) these are difficult to handel and it also lead to overfitting
- uneven shape of array , ML will works only on the fixed size of array
- oov (out of vocabulary problem) testing data may have the new word eg- Hello campusx people
- no capturing of semantic meaning

# Bag of Word 
It best perform in Text Classification eg- Spam classification, News Classification

(Library- from sklearn.feature_extraction.text import CountVectorizer)


Steps-
1. Create Vocabulary from corpus
2. from ech document check How many time each word came in the document here intution is: in similar docs similar type of words will come in same frequecy. (Here order and context of words in sentence does not matters)

Document   | Text                |People | Watch | campusx| write| comment|
:---------|:---------------------|:----------------|:-----|:------|:-------|:-----|
| D1      | People watch campusx  | 1    |1      |1       |0     |0       | 
| D2      | campusx watch campusx |0    |1      |2       |0     |0       | 
| D3      | People write comment  | 1    |0      |0       |1     |1       |  
| D4     | campusx write comment  | 0    |0      |1       |1     |1       |  
| D5     | watch campusx write comment  | 0    |1      |1       |1     |1       | 
##

Q. How Semantic meaning is captured here?
Ans- We are converting each doc in v dimentional vector(5-D in this case)

### Problems of One Hot Encoder Solved by Bag of Words
- Shape of vector will not change for any input
- OOV( out of vocabulary) new words in the testing data will not effect vector
- Semantic relation can be captures frequncy of different words

### Flaws
- Sparsity is still present(difficult to handel and problem of overfitting)
- New words are ignored but they may contain usefull informations
- Squence and ordering in English contains the meaning, however bag of words ignore order and sequencing.
- Big changes by small words can not be handelled by bag of words.
eg- V1= "This is a very good movie." and V2="This is not a very good Movie"  by the logic of bag of words these two vectors V1 and V2 should be very close. however they are just opposite sentiment

In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.DataFrame({'text':['People watch campusx','campusx watch campusx', 'People write comment', 'campusx write comment'], 'Output':[1,1,0,0]})

In [4]:
df

text  Output
0   People watch campusx       1
1  campusx watch campusx       1
2   People write comment       0
3  campusx write comment       0

In [5]:
from sklearn.feature_extraction.text import CountVectorizer
cv= CountVectorizer() #Making object

In [6]:
bow = cv.fit_transform(df['text']) #fitting and data

In [7]:
cv.vocabulary_

{'people': 2, 'watch': 3, 'campusx': 0, 'write': 4, 'comment': 1}

In [10]:
# Printing array formed by bag of words technique
#here squence is [campusx,  comment,  people,  watch,  write]
print(bow[0].toarray())
print(bow[1].toarray())

[[1 0 1 1 0]]
[[2 0 0 1 0]]


In [15]:
# trasnformimg new data that also has new words
cv.transform(['campusx watch and write comment of the campusx']).toarray()

array([[2, 1, 0, 1, 1]], dtype=int64)